In [94]:
class Vertex:
    def __init__(self,key,color=None):
        self.id = key
        self.connectedTo = {}
        self.color = color
    def addNeighbor(self,nbr,weight=0):
        self.connectedTo[nbr] = weight
    def __str__(self):
        return str(self.id) + "connected to" + str([x.id for x in self.connectedTo])
    def getConnections(self):
        return self.connectedTo.keys()
    def getId(self):
        return self.id
    def getWeight(self,nbr):
        return self.connectedTo[nbr]
    def setColor(self,color):
        self.color = color
    def getColor(self):
        return self.color   
    
class Graph:
    def __init__(self):
        self.vertList = {}
        self.numVertices = 0
    def addVertex(self,key):
        self.numVertices = self.numVertices + 1
        newVertex = Vertex(key)
        self.vertList[key] = newVertex
        return newVertex
    def getVertex(self,n):
        if n in self.vertList:
            return self.vertList[n]
        else:
            return None
    def __contains__(self,n):
        return n in self.vertList
    def addEdge(self,f,t,cost=0):
        if f not in self.vertList:
            nv = self.addVertex(f)
        if t not in self.vertList:
            nv = self.addVertex(t)
        self.vertList[f].addNeighbor(self.vertList[t],cost)
    def getVertices(self):
        return self.vertList.keys()
    def __iter__(self):
        return iter(self.vertList.values())

In [17]:
g = Graph()
for i in range(6):
    g.addVertex(i)

In [18]:
print(g.vertList)
g.addEdge(0,1,5)
g.addEdge(0,5,2)
g.addEdge(1,2,4)
g.addEdge(2,3,9)
g.addEdge(3,4,7)
g.addEdge(3,5,3)
g.addEdge(4,0,1)
g.addEdge(5,4,8)
g.addEdge(5,2,1)
for v in g:
    for w in v.getConnections():
        print ("(%s,%s)" % (v.getId(),w.getId()))
        print (v.getWeight(w))

{0: <__main__.Vertex object at 0x000001F52BE4B0A0>, 1: <__main__.Vertex object at 0x000001F52BE4B730>, 2: <__main__.Vertex object at 0x000001F52BE4B7F0>, 3: <__main__.Vertex object at 0x000001F52BE4BF10>, 4: <__main__.Vertex object at 0x000001F52BE4B1F0>, 5: <__main__.Vertex object at 0x000001F52BE4BF40>}
(0,1)
5
(0,5)
2
(1,2)
4
(2,3)
9
(3,4)
7
(3,5)
3
(4,0)
1
(5,4)
8
(5,2)
1


In [20]:
#骑士周游问题 深度优先搜索求解
#建立合法步骤
def genLegalMoves(x,y,bdSize):
    newMoves = []
    moveOffsets = [(-1,-2),(-1,2),(-2,-1),(-2,1),\
                  (1,-2),(1,2),(2,-1),(2,1)]
    for i in moveOffsets:
        newX = x + i[0]
        newY = y + i[1]
        if legalCoord(newX,bdSize) and legalCoord(newY,bdSize):
            newMoves.append((newX,newY))
    return newMoves
def legalCoord(x,bdSize):
    if x >= 0 and x < bdSize:
        return True
    else: 
        return False
#建立图
def knightGraph(bdSize):
    ktGraph = Graph()
    for row in range(bdSize):
        for col in range(bdSize):
            nodeId = posToNodeId(row,col,bdSize)
            newPositions = genLegalMoves(row,col,bdSize)
            for e in newPositions:
                nid = posToNodeId(e[0],e[1],bdSize)
                ktGraph.addEdge(nodeId,nid)
    return ktGraph
def posToNodeId(row,col,bdSize):
    return row*bdSize + col
#周游suanfa
def knightTour(n,path,u,limit):
    u.setColor('gray')
    path.append(u)
    if n < limit:
        nbrList = list(u.getConnections())
        i = 0
        done = False
        while i < len(nbrList) and not done:
            if nbrList[i].getColor() == 'white':
                done = knightTour(n+1,path,nbrList[i],limit)
            i = i + 1
        if not done:
            path.pop()
    else:
        done = true
    return done



In [23]:
myGraph = knightGraph(5)
u = myGraph.getVertex(0)
print(u.getId())
path = []
knightTour(0,path,u,24)
print(path)

0
[]


In [30]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
as1 = np.sum(a**2, axis=1, keepdims=True)
as2 = np.sum(a**2, axis=1)
print(a.T)
print(as1)
print(as2)
s3 = as1 + as2
print(s3)
as3 = 2.a.dot()

[[14]
 [77]]
[14 77]
[[ 28  91]
 [ 91 154]]


In [36]:
a = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
a_folds = []
a_folds = np.array_split(a,5)
print(a_folds)
#if idx != i for line in x

[array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]])]


In [45]:
for i in range(5):
    val_a = [line for idx, x in enumerate(a_folds) if idx!= i for line in x] 
    print(val_a)


[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3]), array([4, 5, 6])]


In [82]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print("a:",a)
b = a[[[0,1,2],[0,1,2]]].T
print(b.shape)
a = a.reshape((3,-1))
print(a.shape)
print("a:",a)
#c = a - b.T
print("c",c)
#c = np.array([[1,2,3,4],[4,5,6,7],[1,2,3,4]])
#d = c - b.T
#print("c",c)
#print("d",d)

a: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(3,)
(3, 10)
a: [[1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]]
c [[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]]


<ipython-input-82-5432e5483e89>:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[[[0,1,2],[0,1,2]]].T


In [68]:
arr = np.arange(12).reshape((3,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [83]:
#作业一寻找法官
def findJudge(N,trust):
    count = [0] * (N+1)
    for i,j in trust:
        count[i] -= 1
        count[j] += 1
    for i in range(1,N+1):
        if count[i] == N-1:
            return i
    return -1

N = int(input())
trust = eval(input())
print(findJudge(N,trust))

4
[[1,3],[1,4],[2,3],[2,4],[4,3]]
3


In [85]:
#作业二远离大陆
def maxDistance(grid):
    n,m = len(grid),len(grid[0])
    dist = [[float('inf') for _ in range(m)] for _ in range(n)]
    visited = [[False for _ in range(m)] for _ in range(n)]
    q = []
    cnt = 0
    ans = 0
    tot = n*m
    for i in range(n):
        for j in range(m):
            if grid[i][j]:
                print(grid[i][j])
                dist[i][j] = 0
                visited[i][j] = True
                q.append((i,j))
                cnt += 1
    if cnt == tot or cnt == 0:
        return -1
    while q:
        x, y = q.pop(0)
        for i,j in [(x+1,y),(x-1,y),(x,y+1),(x,y-1)]:
            if 0 <= i <n and 0 <= j < m and not visited[i][j]:
                dist[i][j] = min(dist[i][j],dist[x][y]+1)
                ans = max(ans,dist[i][j])
                visited[i][j] = True
                q.append((i,j)) 
    return ans

grid = eval(input())
print(maxDistance(grid))

[[1,0,1],[0,0,0],[1,0,1]]
1
1
1
1
2


In [91]:
#作业三 钥匙与房间 深度优先求解
def canVisitAll(rooms):
    room_map = {0}
    def enterroom(keys):
        for key in keys:
            if key not in room_map:
                room_map.add(key)
                enterroom(rooms[key])
            else:
                pass
        return
    enterroom(rooms[0])

    return len(room_map) == len(rooms)

rooms = eval(input())
print(canVisitAll(rooms))


print(type(room_map))


NameError: name 'room_map' is not defined

In [92]:
#作业三 钥匙与房间 广度优先求解
def canVisitAll(rooms):
    visited, queue = {0},[0]
    while queue:
        room_index = queue.pop()
        for key in rooms[room_index]:
            if key not in visited:
                visited.add(key)
                queue.insert(0,key)
    return len(visited) == len(rooms)

rooms = eval(input())
print(canVisitAll(rooms))

[[1],[2],[3],[]]
True


In [95]:
#通用的深度优先算法
class DFSGraph(Graph):
    def __init__(self):
        super().__init__()
        self.time = 0
        
    def dfs(self):
        for aVertex in self:
            aVertex.setColor('white')
            aVertex.setPred(-1)
        for aVertex in self:
            if aVertex.getColor() == 'white':
                self.dfsvisit(aVertex)
    
    def dfsvisit(self,startVertex):
        startVertex.setColor('gray')
        self.time += 1
        startVertex.setDiscovery(self.time)
        for nextVertex in startVertex.getConnections():
            if nextVertex.getColor() == 'white':
                nextVertex.setPred(startVertex)
                self.dfsvisit(nextVertex)
        startVertex.setColor('black')
        startVertex.setFinish(self.time)

In [101]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

#print(x)
print(w.shape)
#print(b)

(120, 3)


In [104]:
np.random.seed(231)
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
b = np.random.randn(5)
dout = np.random.randn(10, 5)
num_inputs = x.shape[0]
input_shape = x.shape[1:]
print(input_shape)
x = x.reshape(num_inputs,np.prod(input_shape)) #(N, d1, ..., d_k)->(N, D)
dx = dout.dot(w.T) #(N, M)*(M,D)
dx = dx.reshape(num_inputs,*input_shape)
print(dx.shape)

(2, 3)
(10, 2, 3)


In [109]:
a = {'dog':123,'cat':321}
print(a['dog'])

123


In [5]:
params = {}
num_hiddenlayers = 2
for i in range(num_hiddenlayers):
    params['W%d' %(i+1)] = i
    params['b%d' %(i+1)] = 0
print(params)    

{'W1': 0, 'b1': 0, 'W2': 1, 'b2': 0}


In [3]:
print('W%d' %(6/3))

W 2


In [7]:
import numpy as np
np.random.seed(231)
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
out = np.reshape(x,(x.shape[0],-1)).dot(w)
print(x.shape)

(10, 2, 3)


In [11]:
import numpy as np
H1 = np.random.rand(4,3)
U1 = (np.random.rand(4,3) < 0.5)/0.5
print(H1)
print(U1)
H1 *= U1
print(H1)

[[0.33922618 0.22428096 0.37612373]
 [0.95794971 0.3448939  0.54539387]
 [0.28226922 0.4131902  0.5687149 ]
 [0.32953763 0.43846751 0.64789432]]
[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 2.]
 [2. 2. 2.]]
[[0.67845235 0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         1.1374298 ]
 [0.65907527 0.87693502 1.29578864]]


In [12]:
H1 = np.random.rand(4,3)
print(H1)
H1 -= np.max(H1,axis=1,keepdims=True)
print(H1)

[[0.97261325 0.66816873 0.00990244]
 [0.84867403 0.47975337 0.3732424 ]
 [0.20889482 0.80759984 0.2979658 ]
 [0.67294893 0.99021491 0.10040144]]
[[ 0.         -0.30444452 -0.96271081]
 [ 0.         -0.36892067 -0.47543163]
 [-0.59870502  0.         -0.50963404]
 [-0.31726598  0.         -0.88981347]]


In [13]:
import sys
        !{sys.executable} --version
    

IndentationError: unexpected indent (<ipython-input-13-87db04bafe58>, line 2)